### ISSUE TITLE
create patient registration*

### ISSUE THREAD

**Issue by benichister** [adityawa/Klinik#12]
create form to add/edit patient into each clinic.
spec : 
1. field using table patient
2. mandatory field : Name, Gender, Birthdate
3. key using name patient (alphabet only) and birth date. if there are some data has same value of that 2 field, system will show notification that patient potentially have already registered. will use existing data or not. if use existing data choose, goto process loket.
4. MRCode will be generated by system for new input. format : yymmiii
5. type : Genera; / Company
6. If company : 
   a. if already exist, check refference employee id number --> must be filled
   b. if new data, input employee ID number ( can search data using name)
7. MRCode can edit by admin manually using special privilege
8. after save, it will store data in patientclinic based on clinic that register that patient.

[generateScriptDB.zip](https://github.com/adityawa/Klinik/files/2959247/generateScriptDB.zip)

**Comment by benichister** [comment]
@adityawa

**Comment by adityawa** [comment]
this task was done
