### ISSUE TITLE
Create API Employee

### ISSUE THREAD

**Issue by benichister** [adityawa/Klinik#13]
Create API to insert employee data.
spec : 

- [ ] check token valid or not, to process data

- [ ] insert data using format (start table employee) EmpID,EmpName,BirthDate,Relationship(table FamilyRelationship use code), Gender, KTPNumber, HPNumber, lastEmpID ,(start table employeeassignment) JointDate (field StartDate), Department, BusinessUnit, Region, EmpStatus (table EmployeeStatus use code)

if empID exist --> update employee table
{
  if joint date exist with empID{
    update employeeassignment
  }else{
    update last employeeassignment set EndDate = joindate
    insert employeeassignment
  }
  if empStatus <> status in employee{
    update employee field status
  }
}else{
  if lastEmpdID filled{
      set lastEmpdID in ID employee, set status = resign, and employeeassignment endate = joindate
      update employee for all reffeployeeID = newemployeeID
      insert employee and employeeassignment
  }
  else{
     if Relationship <> 'E'
       insert employee with reffemployeeID = empID and set employee.empID = empdID + code in familyreference
     else
        insert employee and employeeassignment
  }
}
[case employee.xlsx](https://github.com/adityawa/Klinik/files/2973534/case.employee.xlsx)

**Comment by adityawa** [comment]
the task is completed, i already push my code into Git repo. please check
