### ISSUE TITLE
Form Pre Examine

### ISSUE THREAD

**Issue by benichister** [adityawa/Klinik#23]
1. membuat menu untuk menampilkan daftar hasil registrasi ( tanpa ada create ) yang sumbernya dari loket
2. menu tersebut bisa pilih selected by poli atau bisa all.
3. list tersebut diberikan informasi flag, mana yang sudah pre examine dan yang belum. default filter by yang belum. data yang flash sudah pre-examine masih dapat diedit juga dengan pilih combo status menjadi sudah. filter waktu pada list mengikuti antrian yang dibuat mas helmy.
4. saat di klik proses, cek data di queuepoli based on tanggal,patientid, clinicid cek ke formmedical cek dari startdate,patientid,clinicid untuk mendapatkan formmedicalid
5. menstrualdate dan KBdate khusus wanita saja

**Comment by adityawa** [comment]
DONE, please test
